// automatically generated by the FlatBuffers compiler, do not modify

package poker.io.codec.protocol;

public final class PROC_MENU_TYPE {
  private PROC_MENU_TYPE() { }
  public static final byte FIRST = 0;
  public static final byte NORMAL = 1;
  public static final byte ALLIN = 2;

  public static final String[] names = { "FIRST", "NORMAL", "ALLIN", };

  public static String name(int e) { return names[e]; }
}

