// automatically generated by the FlatBuffers compiler, do not modify

package poker.io.codec.protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PROC_Poker extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static PROC_Poker getRootAsPROC_Poker(ByteBuffer _bb) { return getRootAsPROC_Poker(_bb, new PROC_Poker()); }
  public static PROC_Poker getRootAsPROC_Poker(ByteBuffer _bb, PROC_Poker obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PROC_Poker __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte procTableType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table procTable(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createPROC_Poker(FlatBufferBuilder builder,
      byte procTable_type,
      int procTableOffset) {
    builder.startTable(2);
    PROC_Poker.addProcTable(builder, procTableOffset);
    PROC_Poker.addProcTableType(builder, procTable_type);
    return PROC_Poker.endPROC_Poker(builder);
  }

  public static void startPROC_Poker(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addProcTableType(FlatBufferBuilder builder, byte procTableType) { builder.addByte(0, procTableType, 0); }
  public static void addProcTable(FlatBufferBuilder builder, int procTableOffset) { builder.addOffset(1, procTableOffset, 0); }
  public static int endPROC_Poker(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishPROC_PokerBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedPROC_PokerBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PROC_Poker get(int j) { return get(new PROC_Poker(), j); }
    public PROC_Poker get(PROC_Poker obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

