// automatically generated by the FlatBuffers compiler, do not modify

package poker.io.codec.protocol;

public final class PROC_BATTING_TYPE {
  private PROC_BATTING_TYPE() { }
  public static final byte CHECK = 0;
  public static final byte BBING = 1;
  public static final byte HALF = 2;
  public static final byte FULL = 3;
  public static final byte CALL = 4;
  public static final byte DDADANG = 5;
  public static final byte DIE = 6;

  public static final String[] names = { "CHECK", "BBING", "HALF", "FULL", "CALL", "DDADANG", "DIE", };

  public static String name(int e) { return names[e]; }
}

