// automatically generated by the FlatBuffers compiler, do not modify

package poker.io.codec.protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PROC_User extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static PROC_User getRootAsPROC_User(ByteBuffer _bb) { return getRootAsPROC_User(_bb, new PROC_User()); }
  public static PROC_User getRootAsPROC_User(ByteBuffer _bb, PROC_User obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PROC_User __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String pwd() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pwdAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer pwdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String coinStr() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer coinStrAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer coinStrInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public boolean isWaiting() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateIsWaiting(boolean isWaiting) { int o = __offset(12); if (o != 0) { bb.put(o + bb_pos, (byte)(isWaiting ? 1 : 0)); return true; } else { return false; } }

  public static int createPROC_User(FlatBufferBuilder builder,
      int idOffset,
      int nameOffset,
      int pwdOffset,
      int coinStrOffset,
      boolean isWaiting) {
    builder.startTable(5);
    PROC_User.addCoinStr(builder, coinStrOffset);
    PROC_User.addPwd(builder, pwdOffset);
    PROC_User.addName(builder, nameOffset);
    PROC_User.addId(builder, idOffset);
    PROC_User.addIsWaiting(builder, isWaiting);
    return PROC_User.endPROC_User(builder);
  }

  public static void startPROC_User(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addPwd(FlatBufferBuilder builder, int pwdOffset) { builder.addOffset(2, pwdOffset, 0); }
  public static void addCoinStr(FlatBufferBuilder builder, int coinStrOffset) { builder.addOffset(3, coinStrOffset, 0); }
  public static void addIsWaiting(FlatBufferBuilder builder, boolean isWaiting) { builder.addBoolean(4, isWaiting, false); }
  public static int endPROC_User(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PROC_User get(int j) { return get(new PROC_User(), j); }
    public PROC_User get(PROC_User obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

