// automatically generated by the FlatBuffers compiler, do not modify

package poker.io.codec.protocol;

public final class PROC_HAND_RANK_TYPE {
  private PROC_HAND_RANK_TYPE() { }
  public static final byte NO_PAIR = 0;
  public static final byte ONE_PAIR = 1;
  public static final byte TWO_PAIR = 2;
  public static final byte TRIPLE = 3;
  public static final byte STRAIGHT = 4;
  public static final byte BACK_STRAIGHT = 5;
  public static final byte MOUNTAIN = 6;
  public static final byte FLUSH = 7;
  public static final byte FULL_HOUSE = 8;
  public static final byte FOUR_CARD = 9;
  public static final byte STRAIGHT_FLUSH = 10;
  public static final byte BACK_STRAIGHT_FLUSH = 11;
  public static final byte ROYAL_STRAIGHT_FLUSH = 12;
  public static final byte ALL_DIE = 13;

  public static final String[] names = { "NO_PAIR", "ONE_PAIR", "TWO_PAIR", "TRIPLE", "STRAIGHT", "BACK_STRAIGHT", "MOUNTAIN", "FLUSH", "FULL_HOUSE", "FOUR_CARD", "STRAIGHT_FLUSH", "BACK_STRAIGHT_FLUSH", "ROYAL_STRAIGHT_FLUSH", "ALL_DIE", };

  public static String name(int e) { return names[e]; }
}

