// automatically generated by the FlatBuffers compiler, do not modify

package poker.io.codec.protocol;

public final class PROC_UnionTable {
  private PROC_UnionTable() { }
  public static final byte NONE = 0;
  public static final byte PROC_Login = 1;
  public static final byte PROC_Room_Enter = 2;
  public static final byte PROC_Room_Ready = 3;
  public static final byte PROC_Room_Exit = 4;
  public static final byte PROC_Batting = 5;
  public static final byte PROC_GAME_START = 6;
  public static final byte PROC_ChoiceCard = 7;
  public static final byte PROC_PushCard = 8;
  public static final byte PROC_GAME_END = 9;
  public static final byte PROC_JACKPOT = 10;

  public static final String[] names = { "NONE", "PROC_Login", "PROC_Room_Enter", "PROC_Room_Ready", "PROC_Room_Exit", "PROC_Batting", "PROC_GAME_START", "PROC_ChoiceCard", "PROC_PushCard", "PROC_GAME_END", "PROC_JACKPOT", };

  public static String name(int e) { return names[e]; }
}

