// automatically generated by the FlatBuffers compiler, do not modify

package ache.io.codec.protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PROC_User extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static PROC_User getRootAsPROC_User(ByteBuffer _bb) { return getRootAsPROC_User(_bb, new PROC_User()); }
  public static PROC_User getRootAsPROC_User(ByteBuffer _bb, PROC_User obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PROC_User __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String said() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer saidAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer saidInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String name() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createPROC_User(FlatBufferBuilder builder,
      int idOffset,
      int saidOffset,
      int nameOffset) {
    builder.startTable(3);
    PROC_User.addName(builder, nameOffset);
    PROC_User.addSaid(builder, saidOffset);
    PROC_User.addId(builder, idOffset);
    return PROC_User.endPROC_User(builder);
  }

  public static void startPROC_User(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addSaid(FlatBufferBuilder builder, int saidOffset) { builder.addOffset(1, saidOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(2, nameOffset, 0); }
  public static int endPROC_User(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PROC_User get(int j) { return get(new PROC_User(), j); }
    public PROC_User get(PROC_User obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

