// automatically generated by the FlatBuffers compiler, do not modify

package ache.io.codec.protocol;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PROC_Msg extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static PROC_Msg getRootAsPROC_Msg(ByteBuffer _bb) { return getRootAsPROC_Msg(_bb, new PROC_Msg()); }
  public static PROC_Msg getRootAsPROC_Msg(ByteBuffer _bb, PROC_Msg obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PROC_Msg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String msg() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer msgAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer msgInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createPROC_Msg(FlatBufferBuilder builder,
      int msgOffset) {
    builder.startTable(1);
    PROC_Msg.addMsg(builder, msgOffset);
    return PROC_Msg.endPROC_Msg(builder);
  }

  public static void startPROC_Msg(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addMsg(FlatBufferBuilder builder, int msgOffset) { builder.addOffset(0, msgOffset, 0); }
  public static int endPROC_Msg(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PROC_Msg get(int j) { return get(new PROC_Msg(), j); }
    public PROC_Msg get(PROC_Msg obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

