// automatically generated by the FlatBuffers compiler, do not modify

package ache.io.codec.protocol;

public final class PROC_UnionTable {
  private PROC_UnionTable() { }
  public static final byte NONE = 0;
  public static final byte PROC_Login = 1;
  public static final byte PROC_InitImage = 2;
  public static final byte PROC_ImageList = 3;
  public static final byte PROC_KeyEvent = 4;
  public static final byte PROC_Msg = 5;

  public static final String[] names = { "NONE", "PROC_Login", "PROC_InitImage", "PROC_ImageList", "PROC_KeyEvent", "PROC_Msg", };

  public static String name(int e) { return names[e]; }
}

