// automatically generated by the FlatBuffers compiler, do not modify

package ache.io.codec.protocol;

public final class PROC_KEY_EVENT_TYPE {
  private PROC_KEY_EVENT_TYPE() { }
  public static final byte PRESSED = 0;
  public static final byte RELEASED = 1;

  public static final String[] names = { "PRESSED", "RELEASED", };

  public static String name(int e) { return names[e]; }
}

